# Set up of the Role for the Application Access Management.

apiVersion: rbac.authorization.k5s.io/v1beta1  # account for managing Permissions at this Namespace.
kind: ServiceAccount 
metadata:
  name: service-account-user 
  namespace: store-namespace 
  resourceVersion: "2120"

--- 


apiVersion: rbac.authorization.k8s.io/v1beta1  
kind: ClusterRole 
metadata:
  namespace: store-namespace 
  name: store-application-server-role
- apiGroups: ["", "extensions", ""]
  resources: ["pods", "replicasets", "deployments", "services"] 
  verbs: ["*"] 

--- 

apiVersion: rbac.authorization.k8s.io/v1beta1 
kind: ClusterRoleBinding 
metadata:
  namespace: store-namespace  
subjects:
  kind: User 
  name: store-application-server-manager 
  apiGroup: ""
roleRef:
  role: store-application-server-role 
  kind: Role   
  apiGroup: ""
