version: "3.8"
services:
  
  test_store_application:
    container_name: test_store_application_server 
    build: ../.
    ports:
      - 8000:8000 
    networks:
      - global_store_network 
    depends_on:
      - test_postgres_store_database 

  test_postgres_store_database:
    container_name: test_postgres_store_database 
    image: postgres:latest 
    environment:
      POSTGRES_DB: store_db 
      POSTGRES_USER: postgres_user 
      POSTGRES_PASSWORD: postgres_password 
    ports:
      - 5435:5435 
    command:
      - -p 5435 
    networks:
      - global_store_network  

networks:
  global_store_network:
    external: true 
    name: global_store_network 