version: "3.8"
services:

  jenkins_server:
    container_name: jenkins-master
    image: jenkins/jenkins:lts 
    user: root
    privileged: true 
    ports:
      - 8080:8080
      - 50000:50000  
    volumes:
      - /var/run/docker.sock/:/var/run/docker.sock 
      - /Users/kirillklimushin/jenkins_home/:/var/jenkins_home 
      - /usr/local/bin/docker/:/usr/bin/docker




