apiVersion: apps/v1 
kind: Deployment 

metadata:
  name: store-application-server
  namespace: store_namespace 
  labels: 
    app: store-application-server

spec:
  hostname: store_application 
  selector:
    matchLabels:  
      app: store-application-server
  template:
    metadata:
      labels: 
        app: store_entrypoint 
    spec:
      containers:
        - name: store_application 
          image: crazycoderrr/store_service 
          envFrom:
            secretRef:
              - name: project-secret-store 
          ports:
            - targetPort: 8005 
              protocol: TCP 
              port: 8005 
          resources:
            requests:
              cpu: "0.5"
              memory: "4Gi"
            limits:
              cpu: "0.7"
              memory: "4Gi"
          hostNetwork: true 
          dnsPolicy: Default

          livenessProbe:
            httpGet:
              path: /healthcheck/
              protocol: HTTP 
              port: 8005 
              startPeriod: 30s 
              initialSeconds: 10
      