apiVersion: apps/v1 
kind: Deployment 

metadata:
  name: store-application-server
  namespace: store-namespace 
  labels: 
    app: store-application-server

spec:
  selector:
    matchLabels:  
      app: store-entrypoint
  template:
    metadata:
      labels: 
        app: store-entrypoint 
    spec:
      containers:
        - name: store_application 
          image: crazycoderrr/store_service 
          envFrom:
            secretRef:
              - name: project-secret-store 
          ports:
            - targetPort: 8005 
              protocol: TCP 
              port: 8005 
          resources:
            requests:
              cpu: "0.5"
              memory: "4Gi"
            limits:
              cpu: "0.7"
              memory: "4Gi"

          # Variables that will determine right server credentials,
          # in order to make a healthcheck with right ip and port credentials.
          env:
            - name: APPLICATION_IP_ADDRESS 
              value: metadata.nodeIp

            - name: APPLICATION_PORT
              value: spec.template.spec.containers.ports[0].port

          livenessProbe:
            exec:
              command: ["curl", "-f", "http://$(APPLICATION_IP_ADDRESS):$(APPLICATION_PORT)"]
              startPeriod: 30s 
              initialSeconds: 10
      