apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata:
  name: ingress-store-network 
  namespace: ingress-namespace 
spec:
  type: NodePort 
  tls:
    - hosts:
      - store.com
    secretName: IngressTLSSecret
  rules:
    host: store.com
    http:
      paths:

        path: "/"
        backend: 
          serviceName: store-application-service  # Accessing Store Service from Outside...
          servicePort: 8010

        path: "/orders/service"  # Accessing Order Service From Outside...
        backend: 
          serviceName: order-application-service 
          servicePort: 8090 