apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata:
  name: ingress-store-network 
spec:
  rules:
    host: store.com
    http:
      paths:
        path: 
        - backend: 
            serviceName: store-application-server
            servicePort: 8080  
    