apiVersion: apps/v1 
kind: Deployment 

metadata: 
  name: store-nginx-server 
  namespace: store_namespace 
  labels:
    type: local 

spec:

  selector:
    matchLabels:
      app: store-nginx-server 

  template:
    app: store-nginx-server 
    spec:

      volumes:
        - name: NginxConfiguration 
          hostPath:
            path: ./nginx/nginx.conf 

      containers:
        - name: nginx-server 
          image: nginx:latest 
          ports:
            - containerPort: 80 
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf 
              name: NginxConfiguration 

          resources:  
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi" 

          livenessProbe:
            httpGet:
              - path: /healtcheck/
                port: 80 
                protocol: HTTP
          
          dnsPolicy: Default 
          hostNetwork: true 
          restartPolicy: onFailure 

