apiVersion: apps/v1 
kind: StatefulSet

metadata:
  app: store-postgresql-database 
  namespace: store-namespace 

spec:
  template:
    spec:
      containers:
        - name: postgresql-database 
          image: postgres
          env:
            - name: POSTGRES_DB 
              valueFrom:
                configMapKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_DB  

            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_USER 

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_PASSWORD 
          ports:
            - TargetPort: 5435 
            - port: 5435 
            - protocol: TCP 
          
          command: ["-p", "5435"]

          volumeMounts:
            - mountPath: var/lib/postgres/data
              name: PostgresDataVolume

      volumes:
        name: PostgresDataVolume
        persistentVolumeClaim:
          claimName: persistent-postgres-claim



