apiVersion: apps/v1 
kind: StatefulSet

metadata:
  app: store-postgresql-database 
  namespace: store-namespace 

spec:
  template:
    metadata:
      app: postgres_application 
    
    spec:
      containers:
        - name: postgresql_database 
          image: postgres
          env:
            - name: POSTGRES_DB 
              valueFrom:
                configMapKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_DB  

            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_USER 

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_PASSWORD 
          ports:
            - containerPort: 5435 
          
          command: ["-p", "5435"]
          dnsPolicy: Default 
          hostNetwork: true  

          volumeMounts:
            - mountPath: PostgresDataVolume 
              path: var/lib/postgresql/data 

        volumes:
          name: PostgresDataVolume
          persistentVolumeClaim:
            claimName: persistent-postgres-claim