apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: postgres-database-volume 
  namespace: store-namespace 
spec:
  StorageClassName: "PostgresVolume"
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnlyOnce 
  resources:
    limits: 
      cpu: "0.5"
      memory: "2Gi"
    requests:
      cpu: "0.5"
      memory: "2Gi"

  gcpPersistentDisk:
    pgType: ex4 
    name: gcePersistentVolumePostgresDisk 
---  

apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: persistent-volume-claim 
  namespace: store-namespace 
spec:
  StorageClassName: "PostgresVolume"
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnlyOnce
  resources:
    limits:
      cpu: "0.5"
      memory: "2Gi"
    requests:
      cpu: "0.5"
      memory: "2Gi"
  gcpPersistentDisk:
    pgType: ex4 
    name: gcePersistentVolumePostgresDisk
---

apiVersion: v1 
kind: Secret 
metadata:
  name: postgres-secret 
  namespace: store-namespace 

type: Opaque 
data:
  POSTGRES_USER: postgres_user 
  POSTGRES_PASSWORD: postgres_password 
  POSTGRES_DB: store_db

--- 

apiVersion: v1 
kind: StatefulSet

metadata:
  app: store-postgresql-database 
  namespace: store-namespace 

spec:
  template:
    spec:
      containers:
        - name: postgresql-database 
          image: postgres
          env:
            - name: POSTGRES_DB 
              valueFrom:
                secretKeyRef:
                  - name: postgres-secret
                    value: POSTGRES_DB  

            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  - name: postgres-secret
                    value: POSTGRES_USER 

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  - name: postgres-config-map 
                    value: POSTGRES_PASSWORD 
          ports:
            - targetPort: 5435 
            - port: 5435 
            - protocol: TCP 
          
          command: ["-p", "5435"]

          imagePullPolicy: Never 

          volumeMounts:
            - mountPath: var/lib/postgres/data
              name: PostgresDataVolume

      volumes:
        name: PostgresDataVolume
        persistentVolumeClaim:
          claimName: persistent-postgres-claim
          