apiVersion: v1 
kind: Service 
metadata:
  name: applicationService 
  namespace: ingress_namespace 
spec:
  type: ClusterIP 
  externalIPs:
    - 192.268.0.10 
  selector:
    matchLabels:
      app: store_entrypoint 
  ports:
    - name: store-application-server
      targetPort: 8005 # port of the Nginx Web Server for the applicaiton.
      port: 8010 # port of the Service
