apiVersion: v1 
kind: Service 
metadata:
  name: rabbitmq-internal-server 
  namespace: rabbitmq_namespace 
spec:
  clusterIP: None 
  template:
    app: rabbitmq-internal-server 
  selector:
    matchLabels:
      app: rabbitmq-internal-server 
  - ports:
    - name: rabbitmq-server 
      - targetPort: 5672 
        port: 5672 
        protocol: TCP  
    - name: rabbitmq-management 
      - targetPort: 15672 
        port: 15672 
        protocol: TCP 



