apiVersion: networking.k8s.io/v1beta1 
kind: Service
metadata:
  name: store-load-balancer 
  namespace: ingress_namespace 
spec:
  type: LoadBalancer 
  - ports:
    - name: store-nginx-server 
      targetPort: 80 
      port: 8010 
