// link to the manifest of the project that has been versioned...
env.DEPLOYMENT_MANIFEST_URL="./application.yaml" // Yaml Manifest that is going to be deployed... 
// All of the Manifests are located inside `kubernetes` directory... 

env.MANIFEST_NAMESPACE="store-namespace" // Namespace of the Yaml Application... 